# Generated by Django 2.2 on 2020-08-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='occupation',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterField(
            model_name='occupation',
            name='fire_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата увольнения'),
        ),
    ]
